spring:
  application:
    name: "attachments"
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:8180/realms/buysell/protocol/openid-connect/certs"
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

buySell:
  config:
    appState: ACTIVE
  test:
    value: "test"

keycloak:
  realm: "buysell"
  resource: "buysell_admin"
  auth-server-url: "http://localhost:8180"
  credentials:
    secret: "**********"

minio:
  defaultBucket: "buysell"
  secretKey: "YU0NnGwHOOOXbggvybcV4F5G4Pa1aSbf2zjMO0gN"
  endpoint: "http://127.0.0.1:9000"
  accessKey: "E6yd6BKVy0nUNJYB48Fe"

logging:
  level:
    ROOT: INFO
    com.wosarch: DEBUG
